# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-01-12 14:41
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('slack', '0002_auto_20170112_1328'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='slackuser',
            name='id',
        ),
        migrations.AlterField(
            model_name='event',
            name='ts',
            field=models.DateField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='event',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='slack.SlackUser'),
        ),
        migrations.AlterField(
            model_name='slackuser',
            name='raw_id',
            field=models.CharField(max_length=255, primary_key=True, serialize=False),
        ),
    ]
