# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-01-12 14:42
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('slack', '0003_auto_20170112_1441'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='subtype',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
